## cflags '-I.'
require 'miniaudio_engine'

require 'c89atomic'
require 'C.arg'
require 'C.stdio'

local result: ma_result
local engine: ma_engine

if C.argc < 2 then
  error("No input file.")
end

result = ma_engine_init(nilptr, &engine)
if result ~= MA_SUCCESS then
  error("Failed to initialize audio engine.")
end

ma_engine_play_sound(&engine, C.argv[1], nilptr)

print("Press Enter to quit...")
C.getchar()

ma_engine_uninit(&engine)
