## cflags '-I.'
require 'miniaudio_engine'

require 'c89atomic'
require 'C.arg'
require 'C.stdio'

local result: ma_result
local engine: ma_engine
local sound: ma_sound

if C.argc < 2 then
  error("No input file.")
end

result = ma_engine_init(nilptr, &engine)
if result ~= MA_SUCCESS then
  error("Failed to initialize audio engine.")
end

result = ma_sound_init_from_file(&engine, C.argv[1], 0, nilptr, &sound)
if result ~= MA_SUCCESS then
  error("Failed to load sound.")
end

result = ma_sound_start(&sound)
if result ~= MA_SUCCESS then
  error("Failed to play sound.")
end

while ma_sound_at_end(&sound) == MA_FALSE do
  -- just wait
end

ma_sound_uninit(&sound)
ma_engine_uninit(&engine)
