require 'glad' -- GLAD must be required before GLFW!
require 'glfw'

local g: float32 = 0.0_f32
local function draw()
  g = g + 0.01_f32
  if g > 1.0_f32 then g = 0.0_f32 end
  glClearColor(1.0,g,0.0,1.0)
  glClear(GL_COLOR_BUFFER_BIT)
end

glfwInit()
local window = glfwCreateWindow(512, 512, "GLFW Window", nilptr, nilptr)
if not window then
  error "Could not create window"
end
glfwMakeContextCurrent(window)
glfwSwapInterval(1)
if gladLoadGL() == 0 then
  error 'Could not initialize GLAD'
end
print('OpenGL loaded:', (@cstring)(glGetString(GL_VERSION)))

while glfwWindowShouldClose(window) == 0 do
  draw()
  glfwSwapBuffers(window)
  glfwPollEvents()
  if glfwGetTime() > 1.0 then
    break
  end
end

glfwTerminate()

print("GLFW OK!")
