require 'sdl2'

if SDL_Init(SDL_INIT_VIDEO) ~= 0 then
  error 'Could not initialize SDL'
end
local window = SDL_CreateWindow(
  "An SDL2 Window",
  SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED,
  512, 512,
  0)
if not window then
  error 'Could not create SDL Window'
end

local renderer = SDL_CreateRenderer(window, -1, 0)
if not renderer then
  error 'Could not create SDL Renderer'
end

SDL_SetRenderDrawColor(renderer, 255, 0, 0, 255);
SDL_RenderClear(renderer)
SDL_RenderPresent(renderer)
SDL_Delay(1000)
SDL_DestroyRenderer(renderer)
SDL_DestroyWindow(window)
SDL_Quit()
